function [cost,perf] = cost_perf_function(price, base_price, ...
                                            power, base_power, ...
                                            mass, base_mass, ...
                                            effic, base_effic, ...
                                            flow, base_flow, ...
                                            time, base_time, ...
                                            vel, base_vel, ...
                                            parameters)
                                        
    base_prob = covid_transmission(base_effic,base_flow,parameters);
    prob = covid_transmission(effic,flow,parameters);

    c1 = 1/3;
    c2 = 1/3;
    c3 = 1/3;
    p1 = 1/2;
    p2 = 1/4;
    p3 = 1/4;

    cost = c1 * price / base_price ...
         + c2 * power / base_power ...
         + c3 * mass / base_mass;

    perf = 2 - p1 * prob / base_prob ...
             - p2 * time / base_time ...
             - p3 * vel / base_vel;
     
end